import { defineConfig } from 'vitest/config';
import path from 'path';

export default defineConfig({
  // Use the automatic JSX runtime so components under test don't need an
  // explicit `import React` (matches the Vite app build). Without this,
  // jsdom component tests hit "React is not defined" for any component that
  // relies on the automatic runtime.
  esbuild: { jsx: 'automatic' },
  test: {
    globals: true,
    environment: 'node',
    include: [
      'tests/now-rank.test.ts',
      'tests/schema.test.ts',
      'tests/utils.test.ts',
      'tests/recall-match.test.ts',
      'tests/doc-field-lookup.test.ts',
      'tests/habit-match.test.ts',
      'tests/reextract-merge.test.ts',
      'tests/chart-data.test.ts',
      'tests/tracker-normalize.test.ts',
      'tests/tracker-entry-update.test.ts',
      'tests/tracker-read-no-write.test.ts',
      'tests/create-tracker-universal.test.ts',
      'tests/medication-refills.test.ts',
      'tests/tracker-presentation.test.ts',
      'tests/liability-calc.test.ts',
      'tests/profile-filter.test.ts',
      'tests/expense-view.test.ts',
      'tests/test-data-filter.test.ts',
      'tests/quick-add.test.ts',
      'tests/mutate-reset-race.test.ts',
      'tests/liability-types.test.ts',
      'tests/liability-recurrence.test.ts',
      'tests/liability-schedule.test.ts',
      'tests/cost-of-ownership.test.ts',
      'tests/profile-scope.test.ts',
      'tests/profile-filter-reconcile.test.ts',
      'tests/useProfileScope.dom.test.tsx',
      'tests/finance-import.test.ts',
      'tests/profile-dedup.test.ts',
      'tests/expense-shaped.test.ts',
      'tests/nutrition-shaped.test.ts',
      'tests/document-linking.test.ts',
      'tests/cache-isolation.test.ts',
      'tests/ownership-model.test.ts',
      'tests/scope.test.ts',
      'tests/reminder-scope.test.ts',
      'tests/calendar-virtual-event-scope.test.ts',
      'tests/ownership.test.ts',
      'tests/asset-rollup.test.ts',
      'tests/asset-classification.test.ts',
      'tests/extraction-normalize.test.ts',
      'tests/ai-parent-resolution.test.ts',
      'tests/dashboard-card-consistency.test.ts',
      'tests/auto-ownership-hook.test.ts',
      'tests/dashboard-filter-perf.test.ts',
      'tests/dashboard-timezone.test.ts',
      'tests/document-preview.test.ts',
      'tests/tracker-name-match.test.ts',
      'tests/tracker-identity.test.ts',
      'tests/tracker-shapes-domain.test.ts',
      'tests/tracker-units.test.ts',
      'tests/entity-naming.test.ts',
      'tests/search-index.test.ts',
      'tests/tracker-health.test.ts',
      'tests/hub-routes.test.ts',
      'tests/profile-fields.test.ts',
      'tests/money-overview.test.tsx',
      'tests/money-popups.test.tsx',
      'tests/entity-classify.test.ts',
      'tests/recurring-dates.test.ts',
      'tests/date-math.test.ts',
      'tests/net-worth-ownership.test.ts',
      'tests/tracker-taxonomy.test.ts',
      'tests/category-canon.test.ts',
      'tests/timezone-dst.test.ts',
      'tests/calendar-occurrences.test.ts',
      'tests/calendar-adapters.test.ts',
      'tests/calendar-capabilities.test.ts',
      'tests/profile-field-canon.test.ts',
      'tests/executive-sections.test.tsx',
      'tests/wellness-metrics.test.ts',
      'tests/wellness-overview.test.tsx',
      'tests/wellness-dynamic.test.ts',
      'tests/query-key-hygiene.test.ts',
      'tests/ai-tool-registry.test.ts',
      'tests/ai-envelope.test.ts',
      'tests/bulk-actions.test.ts',
      'tests/ai-system-tools.test.ts',
      'tests/merge-profiles.test.ts',
      'tests/dashboard-layout-guard.test.ts',
      'tests/notifications-v2.test.ts',
      'tests/medication-doses.test.ts',
      'tests/ai-button-parity.test.ts',
      'tests/action-split.test.ts',
      'tests/bulk-extraction-normalize.test.ts',
      'tests/upcoming-reminders.test.ts',
      'tests/estimation-engine.test.ts',
      'tests/canonical-activity.test.ts',
      'tests/habit-intent.test.ts',
      'tests/mood-detect.test.ts',
      'tests/dashboard-buttons.test.ts',
      'tests/design-kit.test.tsx',
      'tests/typography-hygiene.test.ts',
      'tests/chat-timeout-envelope.test.ts',
      'tests/ai-owner-attribution.test.ts',
      'tests/asset-valuation.test.ts',
      'tests/improve-estimate.test.ts',
      'tests/lookup-value-route.test.ts',
      'tests/cache-bust-predicate.test.ts',
      'tests/recover-wedged-queries.test.ts',
      'tests/resume-refresh.test.ts',
      'tests/recurring-profile-dep.test.ts',
      'tests/curated-persistence.test.ts',
      'tests/model-router.test.ts',
      'tests/chat-frontdoor.test.ts',
      'tests/profile-edit-event-gating.test.ts',
      'tests/profile-edit-no-ai-regen.test.ts',
      'tests/bootstrap-seed-keys.test.ts',
      'tests/documents-page.test.ts',
      'tests/dashboard-popup-perf.test.ts',
      'tests/hub-kpi-strip.test.ts',
    ],
    exclude: ['**/node_modules/**', '**/dist/**', 'tests/full-suite.test.ts', 'tests/critical-flows.test.ts', 'tests/api-e2e.test.ts', 'tests/e2e-dashboard-filters.test.ts'],
    testTimeout: 30000,
  },
  resolve: {
    alias: {
      '@shared': path.resolve(__dirname, 'shared'),
      '@': path.resolve(__dirname, 'client/src'),
    },
  },
});
