-- D265 data repair: registry snake_case keys folded into the model's keys
-- (generated from REGISTRY_KEY_ALIASES in shared/registry-fields.ts). The model
-- key wins when both exist; blank aliases are simply dropped.
UPDATE profiles SET fields = (CASE WHEN (fields ? 'monthlyAmount') AND fields->>'monthlyAmount' IS NOT NULL AND fields->>'monthlyAmount' <> '' THEN fields ELSE CASE WHEN fields->>'monthly_payment' IS NULL OR fields->>'monthly_payment' = '' THEN fields ELSE fields || jsonb_build_object('monthlyAmount', fields->'monthly_payment') END END) - 'monthly_payment' WHERE fields ? 'monthly_payment';
UPDATE profiles SET fields = (CASE WHEN (fields ? 'minimumPayment') AND fields->>'minimumPayment' IS NOT NULL AND fields->>'minimumPayment' <> '' THEN fields ELSE CASE WHEN fields->>'minimum_payment' IS NULL OR fields->>'minimum_payment' = '' THEN fields ELSE fields || jsonb_build_object('minimumPayment', fields->'minimum_payment') END END) - 'minimum_payment' WHERE fields ? 'minimum_payment';
UPDATE profiles SET fields = (CASE WHEN (fields ? 'balance') AND fields->>'balance' IS NOT NULL AND fields->>'balance' <> '' THEN fields ELSE CASE WHEN fields->>'current_balance' IS NULL OR fields->>'current_balance' = '' THEN fields ELSE fields || jsonb_build_object('balance', fields->'current_balance') END END) - 'current_balance' WHERE fields ? 'current_balance';
UPDATE profiles SET fields = (CASE WHEN (fields ? 'balance') AND fields->>'balance' IS NOT NULL AND fields->>'balance' <> '' THEN fields ELSE CASE WHEN fields->>'loan_balance' IS NULL OR fields->>'loan_balance' = '' THEN fields ELSE fields || jsonb_build_object('balance', fields->'loan_balance') END END) - 'loan_balance' WHERE fields ? 'loan_balance';
UPDATE profiles SET fields = (CASE WHEN (fields ? 'originalAmount') AND fields->>'originalAmount' IS NOT NULL AND fields->>'originalAmount' <> '' THEN fields ELSE CASE WHEN fields->>'original_balance' IS NULL OR fields->>'original_balance' = '' THEN fields ELSE fields || jsonb_build_object('originalAmount', fields->'original_balance') END END) - 'original_balance' WHERE fields ? 'original_balance';
UPDATE profiles SET fields = (CASE WHEN (fields ? 'originalAmount') AND fields->>'originalAmount' IS NOT NULL AND fields->>'originalAmount' <> '' THEN fields ELSE CASE WHEN fields->>'original_amount' IS NULL OR fields->>'original_amount' = '' THEN fields ELSE fields || jsonb_build_object('originalAmount', fields->'original_amount') END END) - 'original_amount' WHERE fields ? 'original_amount';
UPDATE profiles SET fields = (CASE WHEN (fields ? 'interestRate') AND fields->>'interestRate' IS NOT NULL AND fields->>'interestRate' <> '' THEN fields ELSE CASE WHEN fields->>'interest_rate' IS NULL OR fields->>'interest_rate' = '' THEN fields ELSE fields || jsonb_build_object('interestRate', fields->'interest_rate') END END) - 'interest_rate' WHERE fields ? 'interest_rate';
UPDATE profiles SET fields = (CASE WHEN (fields ? 'termMonths') AND fields->>'termMonths' IS NOT NULL AND fields->>'termMonths' <> '' THEN fields ELSE CASE WHEN fields->>'loan_term_months' IS NULL OR fields->>'loan_term_months' = '' THEN fields ELSE fields || jsonb_build_object('termMonths', fields->'loan_term_months') END END) - 'loan_term_months' WHERE fields ? 'loan_term_months';
UPDATE profiles SET fields = (CASE WHEN (fields ? 'dueDay') AND fields->>'dueDay' IS NOT NULL AND fields->>'dueDay' <> '' THEN fields ELSE CASE WHEN fields->>'due_date_day' IS NULL OR fields->>'due_date_day' = '' THEN fields ELSE fields || jsonb_build_object('dueDay', fields->'due_date_day') END END) - 'due_date_day' WHERE fields ? 'due_date_day';
UPDATE profiles SET fields = (CASE WHEN (fields ? 'creditLimit') AND fields->>'creditLimit' IS NOT NULL AND fields->>'creditLimit' <> '' THEN fields ELSE CASE WHEN fields->>'credit_limit' IS NULL OR fields->>'credit_limit' = '' THEN fields ELSE fields || jsonb_build_object('creditLimit', fields->'credit_limit') END END) - 'credit_limit' WHERE fields ? 'credit_limit';
UPDATE profiles SET fields = (CASE WHEN (fields ? 'extraPayment') AND fields->>'extraPayment' IS NOT NULL AND fields->>'extraPayment' <> '' THEN fields ELSE CASE WHEN fields->>'extra_payment' IS NULL OR fields->>'extra_payment' = '' THEN fields ELSE fields || jsonb_build_object('extraPayment', fields->'extra_payment') END END) - 'extra_payment' WHERE fields ? 'extra_payment';
UPDATE profiles SET fields = (CASE WHEN (fields ? 'value') AND fields->>'value' IS NOT NULL AND fields->>'value' <> '' THEN fields ELSE CASE WHEN fields->>'current_value' IS NULL OR fields->>'current_value' = '' THEN fields ELSE fields || jsonb_build_object('value', fields->'current_value') END END) - 'current_value' WHERE fields ? 'current_value';
UPDATE profiles SET fields = (CASE WHEN (fields ? 'value') AND fields->>'value' IS NOT NULL AND fields->>'value' <> '' THEN fields ELSE CASE WHEN fields->>'estimated_value' IS NULL OR fields->>'estimated_value' = '' THEN fields ELSE fields || jsonb_build_object('value', fields->'estimated_value') END END) - 'estimated_value' WHERE fields ? 'estimated_value';
UPDATE profiles SET fields = (CASE WHEN (fields ? 'value') AND fields->>'value' IS NOT NULL AND fields->>'value' <> '' THEN fields ELSE CASE WHEN fields->>'appraised_value' IS NULL OR fields->>'appraised_value' = '' THEN fields ELSE fields || jsonb_build_object('value', fields->'appraised_value') END END) - 'appraised_value' WHERE fields ? 'appraised_value';
UPDATE profiles SET fields = (CASE WHEN (fields ? 'value') AND fields->>'value' IS NOT NULL AND fields->>'value' <> '' THEN fields ELSE CASE WHEN fields->>'current_market_value' IS NULL OR fields->>'current_market_value' = '' THEN fields ELSE fields || jsonb_build_object('value', fields->'current_market_value') END END) - 'current_market_value' WHERE fields ? 'current_market_value';
UPDATE profiles SET fields = (CASE WHEN (fields ? 'purchasePrice') AND fields->>'purchasePrice' IS NOT NULL AND fields->>'purchasePrice' <> '' THEN fields ELSE CASE WHEN fields->>'purchase_price' IS NULL OR fields->>'purchase_price' = '' THEN fields ELSE fields || jsonb_build_object('purchasePrice', fields->'purchase_price') END END) - 'purchase_price' WHERE fields ? 'purchase_price';
UPDATE profiles SET fields = (CASE WHEN (fields ? 'purchaseDate') AND fields->>'purchaseDate' IS NOT NULL AND fields->>'purchaseDate' <> '' THEN fields ELSE CASE WHEN fields->>'purchase_date' IS NULL OR fields->>'purchase_date' = '' THEN fields ELSE fields || jsonb_build_object('purchaseDate', fields->'purchase_date') END END) - 'purchase_date' WHERE fields ? 'purchase_date';
UPDATE profiles SET fields = (CASE WHEN (fields ? 'dueDate') AND fields->>'dueDate' IS NOT NULL AND fields->>'dueDate' <> '' THEN fields ELSE CASE WHEN fields->>'next_billing_date' IS NULL OR fields->>'next_billing_date' = '' THEN fields ELSE fields || jsonb_build_object('dueDate', fields->'next_billing_date') END END) - 'next_billing_date' WHERE fields ? 'next_billing_date';
UPDATE profiles SET fields = (CASE WHEN (fields ? 'renewalDate') AND fields->>'renewalDate' IS NOT NULL AND fields->>'renewalDate' <> '' THEN fields ELSE CASE WHEN fields->>'renewal_date' IS NULL OR fields->>'renewal_date' = '' THEN fields ELSE fields || jsonb_build_object('renewalDate', fields->'renewal_date') END END) - 'renewal_date' WHERE fields ? 'renewal_date';
UPDATE profiles SET fields = (CASE WHEN (fields ? 'birthday') AND fields->>'birthday' IS NOT NULL AND fields->>'birthday' <> '' THEN fields ELSE CASE WHEN fields->>'date_of_birth' IS NULL OR fields->>'date_of_birth' = '' THEN fields ELSE fields || jsonb_build_object('birthday', fields->'date_of_birth') END END) - 'date_of_birth' WHERE fields ? 'date_of_birth';
UPDATE profiles SET fields = fields || jsonb_build_object('nextDueDate', fields->'dueDate') WHERE fields ? 'dueDate' AND NOT (fields ? 'nextDueDate') AND type_key IN (SELECT type_key FROM profile_type_definitions WHERE category = 'subscriptions');
