// ── Task occurrences ─────────────────────────────────────────────────────────
// Pure, no I/O.
//
// A recurring task stores ONE row — its next due date — and advances that date
// when the occurrence is completed (shared/recurrence.ts). That is the right
// storage model: it never generates hundreds of future rows, and completing
// this week's chore is not entangled with next week's.
//
// But a calendar has to SHOW next week. Before this module the calendar
// timeline emitted a task exactly once, at its stored due date, so "mow the
// lawn every Tuesday" occupied one Tuesday and every other Tuesday was blank —
// the same invisibility that made timed repeating work feel unsaved.
//
// So: occurrences are projected on the fly from the rule in `tags`, the same
// way recurring EVENTS are expanded. Nothing is written.
//
// Occurrences are generated BY INDEX from the base date rather than by walking
// one step at a time, so a series that started years before the requested
// window costs the same as one that started yesterday, and an old daily series
// cannot exhaust the iteration cap before it reaches the window (the bug that
// once made long-running daily events vanish from the calendar entirely).

import { parseRecurrence, type RecurrenceRule } from "./recurrence";
import { addMonthsClamped, addYearsClamped } from "./date-math";

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
const DAY_MS = 86400000;

const parseLocal = (iso: string) => new Date(iso.slice(0, 10) + "T00:00:00");
const toISO = (d: Date) => d.toLocaleDateString("en-CA");

export interface TaskLike {
  dueDate?: string | null;
  tags?: string[] | null;
  status?: string | null;
}

/** Safety valve: no single task may emit more than this into one window. */
const MAX_OCCURRENCES = 500;

/**
 * The nth occurrence (n = 0 is the base date) of a rule, or null when the
 * cadence is one that has to be walked rather than indexed.
 */
function occurrenceByIndex(base: Date, rule: RecurrenceRule, n: number): Date | null {
  switch (rule.unit) {
    case "day":
      return new Date(base.getTime() + n * rule.interval * DAY_MS);
    case "week":
      return new Date(base.getTime() + n * rule.interval * 7 * DAY_MS);
    case "month":
      return addMonthsClamped(base, n * rule.interval, rule.anchorDay);
    case "year":
      return addYearsClamped(base, n * rule.interval, rule.anchorDay);
    default:
      return null; // "weekday" — Mon–Fri has no closed form, see below
  }
}

/**
 * Every date a task falls on inside [windowStart, windowEnd], inclusive.
 *
 * A one-time task yields its due date (or nothing, if that date is outside the
 * window). A recurring task yields each projected occurrence, stopping at
 * whichever comes first: the window end, the series' `runtil:` date, or its
 * `rcount:` budget net of occurrences already completed.
 *
 * A paused series (`rpaused`) yields only dates already in the past — the same
 * rule the recurring-event expansion uses, so pausing hides what is coming
 * without erasing the history behind it.
 */
export function taskOccurrenceDates(
  task: TaskLike,
  windowStart: string,
  windowEnd: string,
  opts: { todayISO?: string } = {},
): string[] {
  const base = String(task?.dueDate || "").slice(0, 10);
  if (!DATE_RE.test(base) || !DATE_RE.test(windowStart) || !DATE_RE.test(windowEnd)) return [];
  if (windowEnd < windowStart) return [];

  const rule = parseRecurrence(Array.isArray(task?.tags) ? task.tags.map(String) : []);
  const today = opts.todayISO && DATE_RE.test(opts.todayISO) ? opts.todayISO : null;
  const visible = (iso: string) => !(rule.paused && today !== null && iso >= today);

  const out: string[] = [];
  if (base >= windowStart && base <= windowEnd && visible(base)) out.push(base);
  if (!rule.freq || !rule.unit) return out;

  // `rcount:` counts occurrences of the whole series, and `rdone:` records how
  // many are already behind it, so the budget left is what remains from the
  // stored due date forward — index 0 included.
  const budget = rule.count ? Math.max(0, rule.count - rule.done) : Infinity;
  const end = rule.until && DATE_RE.test(rule.until)
    ? (rule.until < windowEnd ? rule.until : windowEnd)
    : windowEnd;
  if (end < base) return out;

  const baseDate = parseLocal(base);

  if (rule.unit === "weekday") {
    // Mon–Fri: 5 occurrences per calendar week, so skip whole weeks up to just
    // before the window and walk only the remainder.
    const cur = new Date(baseDate);
    const gapDays = Math.floor((parseLocal(windowStart).getTime() - baseDate.getTime()) / DAY_MS);
    let n = 0;
    if (gapDays > 14) {
      const weeks = Math.floor((gapDays - 7) / 7);
      cur.setDate(cur.getDate() + weeks * 7);
      n = weeks * 5;
    }
    for (let emitted = 0; emitted < MAX_OCCURRENCES; emitted++) {
      cur.setDate(cur.getDate() + 1);
      if (cur.getDay() === 0 || cur.getDay() === 6) { emitted--; continue; }
      n++;
      if (n >= budget) break;
      const iso = toISO(cur);
      if (iso > end) break;
      if (iso >= windowStart && visible(iso)) out.push(iso);
    }
    return out;
  }

  // Indexed cadences: jump straight to the first index at or before the window
  // rather than counting up to it.
  let start = 1;
  const strideDays =
    rule.unit === "day" ? rule.interval
    : rule.unit === "week" ? rule.interval * 7
    : rule.unit === "month" ? rule.interval * 28
    : rule.interval * 365;
  const gapDays = Math.floor((parseLocal(windowStart).getTime() - baseDate.getTime()) / DAY_MS);
  if (gapDays > strideDays * 2) {
    // One stride early absorbs the month/year approximations above, so no
    // in-window occurrence can be skipped.
    start = Math.max(1, Math.floor(gapDays / strideDays) - 1);
  }

  for (let n = start; n < start + MAX_OCCURRENCES; n++) {
    if (n >= budget) break;
    const d = occurrenceByIndex(baseDate, rule, n);
    if (!d) break;
    const iso = toISO(d);
    if (iso > end) break;
    if (iso >= windowStart && iso !== base && visible(iso)) out.push(iso);
  }
  return out;
}

/**
 * Does this task repeat? Cheap enough to call per row; used to decide whether
 * a calendar item should be labelled as one of a series.
 */
export function taskRepeats(task: TaskLike): boolean {
  return !!parseRecurrence(Array.isArray(task?.tags) ? task.tags.map(String) : []).freq;
}
