/**
 * shared/timezone.ts
 * Centralized timezone utility — single source of truth for all date/time ops.
 *
 * RULE: Every "today", "this month", or date-default in the codebase MUST
 * use these helpers with the user's timezone. NEVER use toISOString().slice(0,10)
 * for user-visible dates — that returns UTC, not the user's local date.
 */

export const DEFAULT_TIMEZONE = 'America/Los_Angeles';

/**
 * Returns YYYY-MM-DD for "today" in the given timezone.
 * This is the canonical "what day is it for the user?" function.
 */
export function getUserToday(timezone: string = DEFAULT_TIMEZONE): string {
  return new Date().toLocaleDateString('en-CA', { timeZone: timezone });
}

/**
 * Returns YYYY-MM for the current month in the given timezone.
 */
export function getUserCurrentMonth(timezone: string = DEFAULT_TIMEZONE): string {
  return new Date().toLocaleDateString('en-CA', { timeZone: timezone }).slice(0, 7);
}

/**
 * Formats a Date object to YYYY-MM-DD in the given timezone.
 */
export function toLocalDateStr(date: Date, timezone: string = DEFAULT_TIMEZONE): string {
  return date.toLocaleDateString('en-CA', { timeZone: timezone });
}

/**
 * Formats a Date object to HH:MM (24h) in the given timezone.
 */
export function toLocalTimeStr(date: Date, timezone: string = DEFAULT_TIMEZONE): string {
  return date.toLocaleTimeString('en-GB', { timeZone: timezone, hour: '2-digit', minute: '2-digit' });
}

/**
 * Parses a YYYY-MM-DD date string to a Date object using noon (T12:00:00).
 * Using noon avoids DST edge cases where midnight can shift to the wrong day.
 * Use this instead of new Date(dateStr) for calendar/event date parsing.
 */
export function parseLocalDate(dateStr: string): Date {
  return new Date(`${dateStr}T12:00:00`);
}

/**
 * Timezone-safe date arithmetic. Adds N days to a YYYY-MM-DD string.
 * Consolidates the two separate addDays implementations in supabase-storage.ts.
 */
/**
 * Calendar day (YYYY-MM-DD) of a date-only string or of an instant, in
 * `timezone`. A bare "YYYY-MM-DD" is returned as-is.
 *
 * Use this for due-date comparisons. `new Date("YYYY-MM-DD")` is UTC midnight,
 * so comparing it against `now` marks anything due TODAY as overdue for the
 * whole day (from 00:00 UTC onward) — compare the strings this returns to
 * getUserToday() instead.
 */
export function localDayOf(
  value: string | Date | null | undefined,
  timezone: string = DEFAULT_TIMEZONE,
): string | null {
  if (!value) return null;
  if (typeof value === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(value)) return value;
  const d = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(d.getTime())) return null;
  try {
    return toLocalDateStr(d, timezone);
  } catch {
    return d.toISOString().slice(0, 10);
  }
}

export function addDays(dateStr: string, days: number): string {
  const d = parseLocalDate(dateStr);
  d.setDate(d.getDate() + days);
  // parseLocalDate reads the date as HOST-local noon, so it must be formatted
  // back in host-local time too. Formatting via toISOString() read the UTC
  // date instead, which is a different calendar day whenever the host's
  // offset is at least 12 hours (Auckland in summer, Kiritimati, Samoa):
  // "tomorrow" came back as today, "yesterday" as two days ago. Servers run
  // in UTC and never noticed; browsers in those zones did.
  return d.toLocaleDateString('en-CA');
}

/**
 * Returns the UTC instant (ISO string) for "today at HH:MM" in the given
 * timezone. Used when the user supplies a bare clock time ("8:15 AM") —
 * composing with the SERVER's local clock would be wrong on UTC hosts.
 */
export function todayAtTimeISO(hours: number, minutes: number, timezone: string = DEFAULT_TIMEZONE): string {
  const ymd = getUserToday(timezone);
  // First guess: interpret the wall-clock time as UTC, then correct by the
  // zone's offset at that instant (standard Intl round-trip trick).
  const guess = new Date(`${ymd}T${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:00Z`);
  const inTz = new Date(guess.toLocaleString('en-US', { timeZone: timezone }));
  const inUtc = new Date(guess.toLocaleString('en-US', { timeZone: 'UTC' }));
  return new Date(guess.getTime() - (inTz.getTime() - inUtc.getTime())).toISOString();
}

// ─── Zone-aware wall-clock arithmetic ────────────────────────────────────────
//
// QA report 2026-07-25: "Reminder times change from 2:00 AM to 1:00 AM after
// daylight-saving transitions."
//
// Cause: a recurring series was generated by adding a fixed 86,400,000 ms per
// occurrence. A calendar day is not always 86.4M ms — the DST "fall back" day
// is 25 hours long — so every occurrence after the transition lands an hour
// earlier on the wall clock. "Every day at 2 AM" is a WALL-CLOCK promise, and
// keeping it means stepping the calendar date and re-composing the same local
// time, never adding a fixed duration.

/** The offset of `timezone` from UTC, in minutes, at a given instant. */
function zoneOffsetMinutes(instant: Date, timezone: string): number {
  // Intl round-trip: format the instant in the target zone and in UTC, then
  // diff. Works for every zone and every DST rule without a tz database.
  const inTz = new Date(instant.toLocaleString("en-US", { timeZone: timezone }));
  const inUtc = new Date(instant.toLocaleString("en-US", { timeZone: "UTC" }));
  return Math.round((inTz.getTime() - inUtc.getTime()) / 60000);
}

export interface ZonedParts {
  /** YYYY-MM-DD in the target zone. */
  date: string;
  /** Wall-clock hour 0–23 in the target zone. */
  hours: number;
  /** Wall-clock minute 0–59 in the target zone. */
  minutes: number;
}

/** Break a UTC instant into its wall-clock parts in `timezone`. */
export function getZonedParts(instant: Date | string | number, timezone: string = DEFAULT_TIMEZONE): ZonedParts {
  const d = instant instanceof Date ? instant : new Date(instant);
  const date = d.toLocaleDateString("en-CA", { timeZone: timezone });
  const hm = d.toLocaleTimeString("en-GB", {
    timeZone: timezone, hour: "2-digit", minute: "2-digit", hour12: false,
  });
  const [h, m] = hm.split(":").map(Number);
  // "24:00" is a legal en-GB rendering of midnight in some engines.
  return { date, hours: (h || 0) % 24, minutes: m || 0 };
}

/**
 * The UTC instant for a wall-clock time on a calendar date in `timezone`.
 *
 * Inverse of `getZonedParts`, with the two standard DST disambiguations:
 *
 *   - AMBIGUOUS (fall-back, 01:30 happens twice): the FIRST occurrence wins.
 *   - NONEXISTENT (spring-forward, 02:30 is skipped when the clock jumps
 *     02:00 → 03:00): resolves FORWARD past the gap, so a 2 AM reminder fires
 *     at 3 AM on that one day rather than 1 AM the previous hour.
 *
 * This matches Temporal's "compatible" disambiguation and what luxon and
 * date-fns-tz do.
 */
export function zonedTimeToUTC(
  dateISO: string,
  hours: number,
  minutes: number,
  timezone: string = DEFAULT_TIMEZONE,
): Date {
  const day = dateISO.slice(0, 10);
  const hh = String(Math.floor(hours)).padStart(2, "0");
  const mm = String(Math.floor(minutes)).padStart(2, "0");
  // Read the wall-clock time as if it were UTC, then subtract the zone's
  // offset AT THAT INSTANT (not today's offset — that's the DST bug).
  const guess = new Date(`${day}T${hh}:${mm}:00Z`);
  const hits = (d: Date) => {
    const p = getZonedParts(d, timezone);
    return p.date === day && p.hours === Math.floor(hours) && p.minutes === Math.floor(minutes);
  };

  const first = new Date(guess.getTime() - zoneOffsetMinutes(guess, timezone) * 60000);
  if (hits(first)) return first;
  // The guess straddled a transition — retry with the offset in effect at the
  // corrected instant.
  const second = new Date(guess.getTime() - zoneOffsetMinutes(first, timezone) * 60000);
  if (hits(second)) return second;
  // Neither lands on the requested wall clock: the local time does not exist
  // (spring-forward gap). `first` uses the pre-transition offset, which places
  // us just past the gap — the forward resolution.
  return first;
}

/**
 * Shift a UTC instant by `days` CALENDAR days in `timezone`, preserving the
 * wall-clock time. `extraMinutes` additionally moves the time-of-day (used for
 * twice/three-times-daily dose slots) and rolls into further days when it
 * crosses midnight.
 *
 * Use this instead of `instant + n * 86400000` for anything the user thinks of
 * as "at 2 AM".
 */
export function addZonedDays(
  instant: Date | string | number,
  days: number,
  timezone: string = DEFAULT_TIMEZONE,
  extraMinutes = 0,
): Date {
  const parts = getZonedParts(instant, timezone);
  const total = parts.hours * 60 + parts.minutes + extraMinutes;
  const dayRoll = Math.floor(total / 1440);
  const minuteOfDay = ((total % 1440) + 1440) % 1440;
  const date = addDays(parts.date, days + dayRoll);
  return zonedTimeToUTC(date, Math.floor(minuteOfDay / 60), minuteOfDay % 60, timezone);
}

// ─── Zone-less datetime parsing ──────────────────────────────────────────────
//
// QA report 2026-07-29 (CRUD-T2-001): chat "remind me to call the plumber at
// 5:51 PM today" persisted a reminder for 10:51 AM — exactly 7 hours early,
// the America/Los_Angeles offset.
//
// Cause: `new Date("2026-07-29T17:51:00")`. A zone-less ISO datetime is read as
// the *host's* local time, and the host is a UTC serverless function — so 5:51
// PM Pacific was stored as 5:51 PM UTC. The same trap sits under every REST
// route that took a browser `<input type="datetime-local">` value, which is
// also zone-less by definition.
//
// The wall clock the user typed is the user's, so it must be composed against
// the USER's zone. Timestamps that DO carry a zone ("...Z", "+02:00") are
// already unambiguous and pass through untouched.

/** True when an ISO-ish datetime string carries no timezone designator. */
export function isZonelessDateTime(input: string): boolean {
  return /^\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}(:\d{2}(\.\d+)?)?$/.test(input.trim());
}

/**
 * Parse a user-supplied datetime, honouring `timezone` for zone-less input.
 *
 * Accepts what the app actually produces: `<input type="datetime-local">`
 * values ("2026-07-29T17:51"), model-generated ISO datetimes without an offset,
 * plain dates ("2026-07-29" → local noon, matching parseLocalDate), and fully
 * qualified instants (passed straight to `new Date`).
 *
 * Returns an Invalid Date for junk, so callers keep using `isNaN(d.getTime())`.
 */
const MONTH_NUMBERS: Record<string, number> = {
  jan: 1, january: 1, feb: 2, february: 2, mar: 3, march: 3, apr: 4, april: 4,
  may: 5, jun: 6, june: 6, jul: 7, july: 7, aug: 8, august: 8,
  sep: 9, sept: 9, september: 9, oct: 10, october: 10, nov: 11, november: 11,
  dec: 12, december: 12,
};

const pad2 = (n: number) => String(n).padStart(2, "0");

/**
 * A natural-language calendar date ("September 1", "Sept 1 2026", "9/1/2026",
 * "1 September") as YYYY-MM-DD, plus any time of day the string carried.
 * Returns null when the string is not a plain calendar date — relative words
 * ("tomorrow", "next Friday") are somebody else's job.
 *
 * A MISSING YEAR resolves against today rather than defaulting to whatever
 * `new Date("September 1")` decides — which is the year 2001, because a bare
 * month/day is parsed as a two-digit year. A date more than 60 days behind
 * today rolls forward a year ("January 3" asked on December 28 means the
 * January that is coming), while a recent past date stays put so backdating
 * ("log it for August 15") still works.
 */
export function parseNaturalCalendarDate(
  raw: string,
  timezone: string = DEFAULT_TIMEZONE,
): { date: string; hours?: number; minutes?: number } | null {
  let s = String(raw || "").trim().toLowerCase();
  if (!s) return null;
  // Leading prepositions: "by September 1", "due on 9/1", "starting March 3".
  s = s.replace(/^(?:by|on|due(?:\s+on)?|before|until|till|after|starting(?:\s+on)?|from|beginning)\s+/i, "").trim();
  // "the 1st of September" → "1 september"
  s = s.replace(/^the\s+/, "").replace(/\s+of\s+/, " ").trim();

  // An optional trailing time: "at 9", "at 9:30 pm", "9pm".
  let hours: number | undefined;
  let minutes: number | undefined;
  const timeMatch = s.match(/[\s,]+(?:at\s+)?(\d{1,2})(?::(\d{2}))?\s*(am|pm)?$/i);
  if (timeMatch && (timeMatch[3] || timeMatch[2])) {
    const h = Number(timeMatch[1]);
    const m = timeMatch[2] ? Number(timeMatch[2]) : 0;
    const mer = timeMatch[3]?.toLowerCase();
    if (h >= 0 && h <= 23 && m >= 0 && m <= 59) {
      hours = mer === "pm" ? (h % 12) + 12 : mer === "am" ? h % 12 : h;
      minutes = m;
      s = s.slice(0, timeMatch.index).trim();
    }
  }
  s = s.replace(/[,]+$/, "").trim();

  const monthNames = Object.keys(MONTH_NUMBERS).join("|");
  let month: number | undefined;
  let day: number | undefined;
  let year: number | undefined;

  // "September 1", "Sept. 1, 2026"
  let m = s.match(new RegExp(`^(${monthNames})\\.?\\s+(\\d{1,2})(?:st|nd|rd|th)?(?:[,]?\\s*(\\d{4}))?$`));
  if (m) { month = MONTH_NUMBERS[m[1]]; day = Number(m[2]); year = m[3] ? Number(m[3]) : undefined; }

  // "1 September", "1st Sept 2026"
  if (month === undefined) {
    m = s.match(new RegExp(`^(\\d{1,2})(?:st|nd|rd|th)?\\s+(${monthNames})\\.?(?:[,]?\\s*(\\d{4}))?$`));
    if (m) { day = Number(m[1]); month = MONTH_NUMBERS[m[2]]; year = m[3] ? Number(m[3]) : undefined; }
  }

  // "9/1/2026", "9-1", "09/01/26" — US month-first, matching how the rest of
  // the app writes dates back to the user.
  if (month === undefined) {
    m = s.match(/^(\d{1,2})[/-](\d{1,2})(?:[/-](\d{2,4}))?$/);
    if (m) {
      month = Number(m[1]); day = Number(m[2]);
      if (m[3]) year = m[3].length === 2 ? 2000 + Number(m[3]) : Number(m[3]);
    }
  }

  if (month === undefined || day === undefined) return null;
  if (month < 1 || month > 12 || day < 1 || day > 31) return null;

  const today = getUserToday(timezone);
  if (year === undefined) {
    year = Number(today.slice(0, 4));
    const candidate = `${year}-${pad2(month)}-${pad2(day)}`;
    const daysBehind = (Date.parse(`${today}T00:00:00Z`) - Date.parse(`${candidate}T00:00:00Z`)) / 86400000;
    if (daysBehind > 60) year += 1;
  }

  const date = `${year}-${pad2(month)}-${pad2(day)}`;
  // Reject impossible days ("February 30") rather than letting them roll over.
  const probe = new Date(`${date}T00:00:00Z`);
  if (isNaN(probe.getTime()) || probe.getUTCDate() !== day || probe.getUTCMonth() + 1 !== month) return null;
  return { date, hours, minutes };
}

export function parseUserDateTime(input: string | Date | number, timezone: string = DEFAULT_TIMEZONE): Date {
  if (input instanceof Date) return input;
  if (typeof input === "number") return new Date(input);
  const s = String(input || "").trim();
  if (!s) return new Date(NaN);
  // Date-only: noon local, so a day never rolls backwards across the offset.
  if (/^\d{4}-\d{2}-\d{2}$/.test(s)) return zonedTimeToUTC(s, 12, 0, timezone);
  if (isZonelessDateTime(s)) {
    const [datePart, timePart] = s.replace(" ", "T").split("T");
    const [hh, mm] = timePart.split(":").map(Number);
    return zonedTimeToUTC(datePart, hh || 0, mm || 0, timezone);
  }
  // NATURAL-LANGUAGE CALENDAR DATES (user report 2026-08-22: "passport renewal
  // task used August 31 instead of September 1").
  //
  // Everything that was not ISO used to fall through to `new Date(s)`, and
  // `new Date("September 1, 2026")` is UTC MIDNIGHT — which is 5pm on August
  // 31st in America/Los_Angeles, so every such date landed a day early for any
  // negative-offset user. The ISO branch above has anchored at noon for
  // exactly this reason since it was written; the spoken form never did.
  const natural = parseNaturalCalendarDate(s, timezone);
  if (natural) {
    return zonedTimeToUTC(
      natural.date,
      natural.hours ?? 12,
      natural.minutes ?? 0,
      timezone,
    );
  }
  return new Date(s);
}

/**
 * Coerce however a clock time arrived into the canonical `HH:MM` (24-hour) a
 * task's `dueTime` stores.
 *
 * Tasks carry a clock time of their own, and that time reaches them from three
 * directions that all used to be handled separately (and inconsistently): a
 * `<input type="time">` value, a model argument that may be "9am" / "9:30 PM" /
 * "09:00", and the time half of a full datetime the model resolved. One parser
 * for all three, so "9 AM" can never be stored as an all-day task because a
 * regex didn't recognise it.
 *
 * Returns null for anything that isn't a time — callers treat that as "no clock
 * time given", i.e. an all-day to-do, rather than guessing midnight.
 */
export function normalizeClockTime(input: unknown): string | null {
  const raw = String(input ?? "").trim();
  if (!raw) return null;
  const pad = (h: number, m: number) =>
    `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}`;

  // The time half of a datetime ("2026-08-11T09:00:00", "2026-08-11 09:00").
  const dt = raw.match(/^\d{4}-\d{2}-\d{2}[T ](\d{1,2}):(\d{2})/);
  if (dt) {
    const h = Number(dt[1]), m = Number(dt[2]);
    return h <= 23 && m <= 59 ? pad(h, m) : null;
  }
  // 12-hour with a meridiem: "9am", "9:30 PM", "12 a.m."
  const ampm = raw.match(/^(\d{1,2})(?::(\d{2}))?\s*(a\.?m\.?|p\.?m\.?)$/i);
  if (ampm) {
    let h = Number(ampm[1]);
    const m = ampm[2] ? Number(ampm[2]) : 0;
    if (h < 1 || h > 12 || m > 59) return null;
    h %= 12;
    if (/^p/i.test(ampm[3])) h += 12;
    return pad(h, m);
  }
  // 24-hour, with or without seconds.
  const h24 = raw.match(/^(\d{1,2}):(\d{2})(?::\d{2})?$/);
  if (h24) {
    const h = Number(h24[1]), m = Number(h24[2]);
    return h <= 23 && m <= 59 ? pad(h, m) : null;
  }
  return null;
}

/**
 * Returns a formatted locale string for the system prompt / human-readable display.
 * e.g. "Tuesday, April 7, 2026 at 6:30 PM"
 */
export function formatDisplayDateTime(timezone: string = DEFAULT_TIMEZONE): string {
  return new Date().toLocaleString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
    hour: 'numeric', minute: '2-digit', hour12: true, timeZone: timezone,
  });
}

/**
 * Returns a short formatted date for display, e.g. "04/07/2026"
 */
export function formatDisplayDate(timezone: string = DEFAULT_TIMEZONE): string {
  return new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: '2-digit', day: '2-digit', timeZone: timezone,
  });
}

/**
 * Returns the timezone label for display, e.g. "Pacific Time" or "Eastern Time"
 */
export function getTimezoneLabel(timezone: string = DEFAULT_TIMEZONE): string {
  const map: Record<string, string> = {
    'America/Los_Angeles': 'Pacific Time',
    'America/Denver': 'Mountain Time',
    'America/Chicago': 'Central Time',
    'America/New_York': 'Eastern Time',
    'America/Anchorage': 'Alaska Time',
    'Pacific/Honolulu': 'Hawaii Time',
    'Europe/London': 'GMT',
    'Europe/Paris': 'Central European Time',
    'Asia/Tokyo': 'Japan Time',
    'Australia/Sydney': 'Australia Eastern Time',
  };
  return map[timezone] || timezone.replace(/_/g, ' ');
}

// ─── Quick-add "when" ───────────────────────────────────────────────────────
//
// The calendar manager's quick-add ("haircut tomorrow at 3pm") only knew
// "YYYY-MM-DD" and "on the 15th", so everything else landed TODAY as an
// all-day event with the whole sentence as its title. This is the one
// place that turns the everyday words into a day and a clock time, in the
// user's zone, and hands back the sentence with those words removed.

const WEEKDAYS = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"];

export interface QuickWhen {
  /** YYYY-MM-DD in the user's zone, when the text named a day. */
  date?: string;
  /** HH:MM (24h), when the text named a clock time. */
  time?: string;
  /** The text with the day/time words removed (for the title). */
  rest: string;
}

export function parseQuickWhen(raw: string, timezone: string = DEFAULT_TIMEZONE): QuickWhen {
  let text = String(raw || "");
  let date: string | undefined;
  let time: string | undefined;
  const today = getUserToday(timezone);
  const cut = (m: RegExpMatchArray) => { text = text.slice(0, m.index!) + " " + text.slice(m.index! + m[0].length); };

  // Clock time: "at 3pm", "3:30 pm", "15:00", "noon", "midnight".
  let m = text.match(/(?:\bat\s+)?\b(\d{1,2})(?::(\d{2}))?\s*(am|pm|a\.m\.|p\.m\.)\b/i)
    || text.match(/(?:\bat\s+)?\b(\d{1,2}):(\d{2})\b(?!\s*(?:am|pm))/i);
  if (m) {
    const h = Number(m[1]), mm = m[2] ? Number(m[2]) : 0;
    const mer = (m[3] || "").toLowerCase().replace(/\./g, "");
    const hh = mer === "pm" ? (h % 12) + 12 : mer === "am" ? h % 12 : h;
    if (hh >= 0 && hh <= 23 && mm >= 0 && mm <= 59 && (mer || m[2])) { time = `${pad2(hh)}:${pad2(mm)}`; cut(m); }
  }
  if (!time) {
    m = text.match(/\b(?:at\s+)?(noon|midnight|midday)\b/i);
    if (m) { time = /noon|midday/i.test(m[1]) ? "12:00" : "00:00"; cut(m); }
  }

  // Day words.
  const rel: Array<[RegExp, (mm: RegExpMatchArray) => string]> = [
    [/\b(?:the\s+)?day\s+after\s+tomorrow\b/i, () => addDays(today, 2)],
    [/\btomorrow\b/i, () => addDays(today, 1)],
    [/\b(?:today|tonight|this\s+(?:morning|afternoon|evening))\b/i, () => today],
    [/\byesterday\b/i, () => addDays(today, -1)],
    [/\bin\s+(\d{1,3})\s+days?\b/i, (mm) => addDays(today, Number(mm[1]))],
    [/\bin\s+(a|one|\d{1,2})\s+weeks?\b/i, (mm) => addDays(today, 7 * (/^\d/.test(mm[1]) ? Number(mm[1]) : 1))],
    [/\bnext\s+week\b/i, () => addDays(today, 7)],
  ];
  for (const [re, fn] of rel) {
    const mm = text.match(re);
    if (mm) { date = fn(mm); cut(mm); break; }
  }
  if (!date) {
    const wd = text.match(/\b(next|this)?\s*(sunday|monday|tuesday|wednesday|thursday|friday|saturday)\b/i);
    if (wd) {
      const target = WEEKDAYS.indexOf(wd[2].toLowerCase());
      const todayDow = new Date(`${today}T12:00:00Z`).getUTCDay();
      let delta = (target - todayDow + 7) % 7;
      if (wd[1] && wd[1].toLowerCase() === "next" && delta === 0) delta = 7;
      date = addDays(today, delta);
      cut(wd);
    }
  }
  if (!date) {
    const iso = text.match(/\b(\d{4}-\d{2}-\d{2})\b/);
    if (iso) { date = iso[1]; cut(iso); }
  }
  if (!date) {
    const monthNames = Object.keys(MONTH_NUMBERS).join("|");
    const nat = text.match(new RegExp(`\\b(?:on\\s+)?((?:${monthNames})\\.?\\s+\\d{1,2}(?:st|nd|rd|th)?(?:,?\\s*\\d{4})?|\\d{1,2}(?:st|nd|rd|th)?\\s+(?:${monthNames})\\.?(?:,?\\s*\\d{4})?|\\d{1,2}[/-]\\d{1,2}(?:[/-]\\d{2,4})?)\\b`, "i"));
    if (nat) {
      const parsed = parseNaturalCalendarDate(nat[1], timezone);
      if (parsed) { date = parsed.date; cut(nat); }
    }
  }

  const rest = text.replace(/\s+/g, " ").replace(/\s+(at|on|,)\s*$/i, "").replace(/^\s*(at|on)\s+/i, "").trim();
  return { date, time, rest };
}
