/**
 * shared/timezone.ts
 * Centralized timezone utility — single source of truth for all date/time ops.
 *
 * RULE: Every "today", "this month", or date-default in the codebase MUST
 * use these helpers with the user's timezone. NEVER use toISOString().slice(0,10)
 * for user-visible dates — that returns UTC, not the user's local date.
 */

export const DEFAULT_TIMEZONE = 'America/Los_Angeles';

/**
 * Returns YYYY-MM-DD for "today" in the given timezone.
 * This is the canonical "what day is it for the user?" function.
 */
export function getUserToday(timezone: string = DEFAULT_TIMEZONE): string {
  return new Date().toLocaleDateString('en-CA', { timeZone: timezone });
}

/**
 * Returns YYYY-MM for the current month in the given timezone.
 */
export function getUserCurrentMonth(timezone: string = DEFAULT_TIMEZONE): string {
  return new Date().toLocaleDateString('en-CA', { timeZone: timezone }).slice(0, 7);
}

/**
 * Formats a Date object to YYYY-MM-DD in the given timezone.
 */
export function toLocalDateStr(date: Date, timezone: string = DEFAULT_TIMEZONE): string {
  return date.toLocaleDateString('en-CA', { timeZone: timezone });
}

/**
 * Formats a Date object to HH:MM (24h) in the given timezone.
 */
export function toLocalTimeStr(date: Date, timezone: string = DEFAULT_TIMEZONE): string {
  return date.toLocaleTimeString('en-GB', { timeZone: timezone, hour: '2-digit', minute: '2-digit' });
}

/**
 * Parses a YYYY-MM-DD date string to a Date object using noon (T12:00:00).
 * Using noon avoids DST edge cases where midnight can shift to the wrong day.
 * Use this instead of new Date(dateStr) for calendar/event date parsing.
 */
export function parseLocalDate(dateStr: string): Date {
  return new Date(`${dateStr}T12:00:00`);
}

/**
 * Timezone-safe date arithmetic. Adds N days to a YYYY-MM-DD string.
 * Consolidates the two separate addDays implementations in supabase-storage.ts.
 */
export function addDays(dateStr: string, days: number): string {
  const d = parseLocalDate(dateStr);
  d.setDate(d.getDate() + days);
  // Return using ISO slice — safe here because we're using noon UTC and only
  // computing the calendar date (not time), so there's no risk of day shift.
  return d.toISOString().slice(0, 10);
}

/**
 * Returns the UTC instant (ISO string) for "today at HH:MM" in the given
 * timezone. Used when the user supplies a bare clock time ("8:15 AM") —
 * composing with the SERVER's local clock would be wrong on UTC hosts.
 */
export function todayAtTimeISO(hours: number, minutes: number, timezone: string = DEFAULT_TIMEZONE): string {
  const ymd = getUserToday(timezone);
  // First guess: interpret the wall-clock time as UTC, then correct by the
  // zone's offset at that instant (standard Intl round-trip trick).
  const guess = new Date(`${ymd}T${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:00Z`);
  const inTz = new Date(guess.toLocaleString('en-US', { timeZone: timezone }));
  const inUtc = new Date(guess.toLocaleString('en-US', { timeZone: 'UTC' }));
  return new Date(guess.getTime() - (inTz.getTime() - inUtc.getTime())).toISOString();
}

// ─── Zone-aware wall-clock arithmetic ────────────────────────────────────────
//
// QA report 2026-07-25: "Reminder times change from 2:00 AM to 1:00 AM after
// daylight-saving transitions."
//
// Cause: a recurring series was generated by adding a fixed 86,400,000 ms per
// occurrence. A calendar day is not always 86.4M ms — the DST "fall back" day
// is 25 hours long — so every occurrence after the transition lands an hour
// earlier on the wall clock. "Every day at 2 AM" is a WALL-CLOCK promise, and
// keeping it means stepping the calendar date and re-composing the same local
// time, never adding a fixed duration.

/** The offset of `timezone` from UTC, in minutes, at a given instant. */
function zoneOffsetMinutes(instant: Date, timezone: string): number {
  // Intl round-trip: format the instant in the target zone and in UTC, then
  // diff. Works for every zone and every DST rule without a tz database.
  const inTz = new Date(instant.toLocaleString("en-US", { timeZone: timezone }));
  const inUtc = new Date(instant.toLocaleString("en-US", { timeZone: "UTC" }));
  return Math.round((inTz.getTime() - inUtc.getTime()) / 60000);
}

export interface ZonedParts {
  /** YYYY-MM-DD in the target zone. */
  date: string;
  /** Wall-clock hour 0–23 in the target zone. */
  hours: number;
  /** Wall-clock minute 0–59 in the target zone. */
  minutes: number;
}

/** Break a UTC instant into its wall-clock parts in `timezone`. */
export function getZonedParts(instant: Date | string | number, timezone: string = DEFAULT_TIMEZONE): ZonedParts {
  const d = instant instanceof Date ? instant : new Date(instant);
  const date = d.toLocaleDateString("en-CA", { timeZone: timezone });
  const hm = d.toLocaleTimeString("en-GB", {
    timeZone: timezone, hour: "2-digit", minute: "2-digit", hour12: false,
  });
  const [h, m] = hm.split(":").map(Number);
  // "24:00" is a legal en-GB rendering of midnight in some engines.
  return { date, hours: (h || 0) % 24, minutes: m || 0 };
}

/**
 * The UTC instant for a wall-clock time on a calendar date in `timezone`.
 *
 * Inverse of `getZonedParts`, with the two standard DST disambiguations:
 *
 *   - AMBIGUOUS (fall-back, 01:30 happens twice): the FIRST occurrence wins.
 *   - NONEXISTENT (spring-forward, 02:30 is skipped when the clock jumps
 *     02:00 → 03:00): resolves FORWARD past the gap, so a 2 AM reminder fires
 *     at 3 AM on that one day rather than 1 AM the previous hour.
 *
 * This matches Temporal's "compatible" disambiguation and what luxon and
 * date-fns-tz do.
 */
export function zonedTimeToUTC(
  dateISO: string,
  hours: number,
  minutes: number,
  timezone: string = DEFAULT_TIMEZONE,
): Date {
  const day = dateISO.slice(0, 10);
  const hh = String(Math.floor(hours)).padStart(2, "0");
  const mm = String(Math.floor(minutes)).padStart(2, "0");
  // Read the wall-clock time as if it were UTC, then subtract the zone's
  // offset AT THAT INSTANT (not today's offset — that's the DST bug).
  const guess = new Date(`${day}T${hh}:${mm}:00Z`);
  const hits = (d: Date) => {
    const p = getZonedParts(d, timezone);
    return p.date === day && p.hours === Math.floor(hours) && p.minutes === Math.floor(minutes);
  };

  const first = new Date(guess.getTime() - zoneOffsetMinutes(guess, timezone) * 60000);
  if (hits(first)) return first;
  // The guess straddled a transition — retry with the offset in effect at the
  // corrected instant.
  const second = new Date(guess.getTime() - zoneOffsetMinutes(first, timezone) * 60000);
  if (hits(second)) return second;
  // Neither lands on the requested wall clock: the local time does not exist
  // (spring-forward gap). `first` uses the pre-transition offset, which places
  // us just past the gap — the forward resolution.
  return first;
}

/**
 * Shift a UTC instant by `days` CALENDAR days in `timezone`, preserving the
 * wall-clock time. `extraMinutes` additionally moves the time-of-day (used for
 * twice/three-times-daily dose slots) and rolls into further days when it
 * crosses midnight.
 *
 * Use this instead of `instant + n * 86400000` for anything the user thinks of
 * as "at 2 AM".
 */
export function addZonedDays(
  instant: Date | string | number,
  days: number,
  timezone: string = DEFAULT_TIMEZONE,
  extraMinutes = 0,
): Date {
  const parts = getZonedParts(instant, timezone);
  const total = parts.hours * 60 + parts.minutes + extraMinutes;
  const dayRoll = Math.floor(total / 1440);
  const minuteOfDay = ((total % 1440) + 1440) % 1440;
  const date = addDays(parts.date, days + dayRoll);
  return zonedTimeToUTC(date, Math.floor(minuteOfDay / 60), minuteOfDay % 60, timezone);
}

/**
 * Returns a formatted locale string for the system prompt / human-readable display.
 * e.g. "Tuesday, April 7, 2026 at 6:30 PM"
 */
export function formatDisplayDateTime(timezone: string = DEFAULT_TIMEZONE): string {
  return new Date().toLocaleString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
    hour: 'numeric', minute: '2-digit', hour12: true, timeZone: timezone,
  });
}

/**
 * Returns a short formatted date for display, e.g. "04/07/2026"
 */
export function formatDisplayDate(timezone: string = DEFAULT_TIMEZONE): string {
  return new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: '2-digit', day: '2-digit', timeZone: timezone,
  });
}

/**
 * Returns the timezone label for display, e.g. "Pacific Time" or "Eastern Time"
 */
export function getTimezoneLabel(timezone: string = DEFAULT_TIMEZONE): string {
  const map: Record<string, string> = {
    'America/Los_Angeles': 'Pacific Time',
    'America/Denver': 'Mountain Time',
    'America/Chicago': 'Central Time',
    'America/New_York': 'Eastern Time',
    'America/Anchorage': 'Alaska Time',
    'Pacific/Honolulu': 'Hawaii Time',
    'Europe/London': 'GMT',
    'Europe/Paris': 'Central European Time',
    'Asia/Tokyo': 'Japan Time',
    'Australia/Sydney': 'Australia Eastern Time',
  };
  return map[timezone] || timezone.replace(/_/g, ' ');
}
