// Regenerate docs/ai-capabilities.md from the live tool registry so the
// "what can the AI do" manifest can never drift from the code.
//   npx tsx scripts/gen-ai-capabilities.ts
import fs from "fs";
import path from "path";
import { TOOL_DEFINITIONS, TOOL_ACTION_MAP, READ_ONLY_TOOLS } from "../server/ai-engine";

const tools = (TOOL_DEFINITIONS as any[]).slice().sort((a, b) => a.name.localeCompare(b.name));
const writes = tools.filter((t) => !READ_ONLY_TOOLS.has(t.name));
const reads = tools.filter((t) => READ_ONLY_TOOLS.has(t.name));

const row = (t: any) => {
  const action = TOOL_ACTION_MAP[t.name] || "retrieve";
  const desc = String(t.description || "").replace(/\s+/g, " ").replace(/\|/g, "\\|").slice(0, 140);
  return `| \`${t.name}\` | \`${action}\` | ${desc} |`;
};

const md = `# Portol AI — capabilities manifest

> Auto-generated by \`scripts/gen-ai-capabilities.ts\` from \`server/ai-engine.ts\`.
> Do not edit by hand. Regenerate after changing \`TOOL_DEFINITIONS\`.

**${tools.length} tools** — ${writes.length} write, ${reads.length} read-only.
The AI chat dispatches these via Anthropic tool-calling (\`processMessage\`), and
\`tests/ai-tool-registry.test.ts\` guards that every tool stays wired.

## Write tools (${writes.length})

| Tool | Action type | Description |
|---|---|---|
${writes.map(row).join("\n")}

## Read-only tools (${reads.length})

| Tool | Action type | Description |
|---|---|---|
${reads.map(row).join("\n")}
`;

const out = path.resolve(process.cwd(), "docs/ai-capabilities.md");
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, md);
console.log(`Wrote ${out} (${tools.length} tools: ${writes.length} write, ${reads.length} read)`);
