// Regenerate docs/ai-crud-parity.md from shared/ai-parity-matrix.ts so the
// "can the AI chat do everything the dashboard can" checklist can never drift
// from the code. tests/ai-button-parity.test.ts enforces the matrix against
// the live tool registry.
//   npx tsx scripts/gen-ai-crud-parity.ts
import fs from "fs";
import path from "path";
import { PARITY_MATRIX, type ParityRow } from "../shared/ai-parity-matrix";

const ICON: Record<ParityRow["status"], string> = {
  covered: "✅",
  added: "🆕",
  planned: "🔜",
  excluded: "🚫",
};

const counts = { covered: 0, added: 0, planned: 0, excluded: 0 } as Record<ParityRow["status"], number>;
for (const r of PARITY_MATRIX) counts[r.status]++;

// Group rows by entity, preserving matrix order.
const groups = new Map<string, ParityRow[]>();
for (const r of PARITY_MATRIX) {
  if (!groups.has(r.entity)) groups.set(r.entity, []);
  groups.get(r.entity)!.push(r);
}

const esc = (s: string) => s.replace(/\|/g, "\\|");
const row = (r: ParityRow) => {
  const tools = r.aiTools.length ? r.aiTools.map((t) => `\`${t}\``).join(", ") : "—";
  const note = r.status === "excluded" ? esc(r.reason || "") : "";
  return `| ${esc(r.operation)} | ${esc(r.ui)} | ${tools} | ${ICON[r.status]} ${r.status} | ${note} |`;
};

const sections = Array.from(groups.entries()).map(([entity, rows]) => `### ${entity}

| Operation | UI surface | AI tool(s) | Status | Notes |
|---|---|---|---|---|
${rows.map(row).join("\n")}`).join("\n\n");

const md = `# Portol AI ↔ Dashboard CRUD parity checklist

> Auto-generated by \`scripts/gen-ai-crud-parity.ts\` from \`shared/ai-parity-matrix.ts\`.
> Do not edit by hand. \`tests/ai-button-parity.test.ts\` enforces this matrix
> against the live tool registry in CI.

**${PARITY_MATRIX.length} operations** — ✅ ${counts.covered} covered · 🆕 ${counts.added} added · 🔜 ${counts.planned} planned · 🚫 ${counts.excluded} excluded by design.

Legend: ✅ the AI chat can do this today · 🆕 added by the CRUD-parity effort ·
🔜 designed, landing in an upcoming batch · 🚫 deliberately not exposed to chat
(reason in Notes).

${sections}
`;

const out = path.resolve(process.cwd(), "docs/ai-crud-parity.md");
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, md);
console.log(`Wrote ${out} (${PARITY_MATRIX.length} rows: ${counts.covered} covered, ${counts.added} added, ${counts.planned} planned, ${counts.excluded} excluded)`);
